apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linstor-cluster
spec:
  values:
    linstorSatelliteConfigurations:
      - name: replicated
        storagePools:
          - name: pool-0
            lvmThinPool:
              volumeGroup: linstor-pool-0
            source:
              hostDevices:
                - /dev/disk/by-path/pci-0000:00:17.0-ata-2
