---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-storage
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 70Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      initContainers:
        - name: init-jellyfin
          image: busybox:stable-musl
          securityContext:
            runAsUser: 0
          command: ["/bin/sh", "-c"]
          args:
            - "mkdir -p /media/{movies,shows}"
          volumeMounts:
            - name: jellyfin-storage
              mountPath: /media
              subPath: media
      containers:
      - image: ghcr.io/jellyfin/jellyfin:10.10.7
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            gpu.intel.com/i915: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: jellyfin
        ports:
        - containerPort: 8096
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /media
          name: jellyfin-storage
          subPath: media
        - mountPath: /config
          name: jellyfin-storage
          subPath: jellyfin-config
        - mountPath: /cache
          name: jellyfin-storage
          subPath: jellyfin-cache
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jellyfin-storage
        persistentVolumeClaim:
          claimName: jellyfin-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: filebrowser
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filebrowser
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - image: docker.io/filebrowser/filebrowser:v2.42.5
        imagePullPolicy: IfNotPresent
        name: filebrowser
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /srv
          name: jellyfin-storage
          subPath: media
        - mountPath: /config
          name: jellyfin-storage
          subPath: filebrowser-config
        - mountPath: /database
          name: jellyfin-storage
          subPath: filebrowser-db
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jellyfin-storage
        persistentVolumeClaim:
          claimName: jellyfin-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jellyfin
  name: jellyfin-http
  namespace: jellyfin
spec:
  ports:
  - name: http
    port: 8096
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: jellyfin
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: filebrowser
  name: filebrowser-http
  namespace: jellyfin
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: filebrowser
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-ui
  namespace: jellyfin
spec:
  parentRefs:
  - name: metal-gateway
    namespace: gateways
    sectionName: imnotaserver.xyz-https
  hostnames:
  - "jellyfin.imnotaserver.xyz"
  rules:
  - backendRefs:
    - name: jellyfin-http
      port: 8096
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: filebrowser-ui
  namespace: jellyfin
spec:
  parentRefs:
  - name: metal-gateway
    namespace: gateways
    sectionName: imnotaserver.xyz-https
  hostnames:
  - "jellyfin-media.imnotaserver.xyz"
  rules:
  - backendRefs:
    - name: filebrowser-http
      port: 8080
