apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linstor-cluster
spec:
  values:
    linstorSatelliteConfigurations:
      - name: replicated
        storagePools:
          - name: pool-0
            lvmThinPool:
              volumeGroup: linstor-pool-0
            source:
              hostDevices:
                - /dev/disk/by-path/virtio-pci-0000:06:00.0
    storageClasses:
      - name: replicated
        reclaimPolicy: Delete
        allowVolumeExpansion: true
        volumeBindingMode: WaitForFirstConsumer
        provisioner: linstor.csi.linbit.com
        parameters:
          linstor.csi.linbit.com/autoPlace: "1"
          linstor.csi.linbit.com/storagePool: pool-0
          linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"