apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./nginx-gateway-fabric.yaml
- ./metrics-server.yaml
- ./piraeus.yaml
- ./local-path-provisioner.yaml
- ./cert-manager.yaml
- ./external-secrets.yaml
